version = 1

exclude_patterns = [
  "/tools/**",
  "/VMS/**",
  "/target/**",
  "/scorecard/**",
  "/scripts/**",
  "/results/**",
  "/data/**"
]

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "8"